// flow-typed signature: 18a3f2f086581cea23eafa08ee135f45
// flow-typed version: <<STUB>>/capture-stream_v0.1.2/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'capture-stream'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'capture-stream' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'capture-stream/index' {
  declare module.exports: $Exports<'capture-stream'>;
}
declare module 'capture-stream/index.js' {
  declare module.exports: $Exports<'capture-stream'>;
}
