// flow-typed signature: 30e02a5e53b5c61220da7ec8927a951d
// flow-typed version: <<STUB>>/to-factory_v1.0.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'to-factory'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'to-factory' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'to-factory/test/index' {
  declare module.exports: any;
}

declare module 'to-factory/test/test' {
  declare module.exports: any;
}

declare module 'to-factory/to-factory' {
  declare module.exports: any;
}

// Filename aliases
declare module 'to-factory/index' {
  declare module.exports: $Exports<'to-factory'>;
}
declare module 'to-factory/index.js' {
  declare module.exports: $Exports<'to-factory'>;
}
declare module 'to-factory/test/index.js' {
  declare module.exports: $Exports<'to-factory/test/index'>;
}
declare module 'to-factory/test/test.js' {
  declare module.exports: $Exports<'to-factory/test/test'>;
}
declare module 'to-factory/to-factory.js' {
  declare module.exports: $Exports<'to-factory/to-factory'>;
}
