// flow-typed signature: c0ab7ec8c2386d709fb7b23fbccb7ff8
// flow-typed version: <<STUB>>/typeov_v1.2.4/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typeov'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typeov' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'typeov/index' {
  declare module.exports: $Exports<'typeov'>;
}
declare module 'typeov/index.js' {
  declare module.exports: $Exports<'typeov'>;
}
